FROM rockylinux:9-minimal AS base

LABEL maintainer="Geon Technologies" \
      description="composite-based components"

RUN microdnf -y update && microdnf -y upgrade

RUN adduser -s /bin/bash composite-dev

FROM base AS build

RUN set -ex; \
    microdnf install -y gcc-toolset-13-gcc-c++; \
    microdnf install -y cmake; \
    microdnf install -y git; \
    microdnf install -y vim; \
    microdnf install -y gdb; \
    microdnf install -y fftw-devel; \
    microdnf install -y numactl-devel; \
    microdnf install -y libatomic; \
    microdnf install -y openssl-devel;

FROM build as dpdk-build
# FROM rockylinux:9 AS dpdk-build

RUN microdnf install -y dnf && \
    dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --set-enabled crb && \
    dnf clean all && \
    rm -rf /var/cache/dnf

RUN dnf install -y dnf-plugins-core
RUN dnf config-manager --set-enabled crb 
RUN dnf update -y && dnf install -y  --allowerasing \ 
    meson \
    ninja-build \
    clang \
    pkg-config \
    lld \
    net-tools \
    pciutils \
    python3-pip \
    wget \
    curl \
    cmake3 

RUN git clone --branch v25.03 https://github.com/DPDK/dpdk.git /dpdk
WORKDIR /dpdk
RUN pip3 install pyelftools
RUN meson setup build --prefix=/opt/dpdk --libdir=lib -Dlibnuma=disabled -Duse_hpet=false -DRTE_LIBRTE_MEMPOOL_STATS=1
RUN ninja -C build
RUN ninja -C build install

FROM build AS project
# DPDK START
# Set environment variables for DPDK
ENV RTE_SDK=/opt/dpdk
ENV RTE_TARGET=x86_64-native-linuxapp-gcc
COPY --from=dpdk-build /dpdk /dpdk
COPY --from=dpdk-build /usr/local/bin /usr/local/bin
COPY --from=dpdk-build /opt/dpdk /opt/dpdk

COPY include /opt/composite-comps/include
COPY src /opt/composite-comps/src
COPY CMakeLists.txt /opt/composite-comps
WORKDIR /opt/composite-comps

ENV PKG_CONFIG_PATH="/opt/dpdk/lib/pkgconfig:$PKG_CONFIG_PATH"
ENV LD_LIBRARY_PATH="/opt/dpdk/lib:$LD_LIBRARY_PATH"

RUN set -ex; \
    . /opt/rh/gcc-toolset-13/enable; \
    cmake -B docker-build \
        -DCOMPOSITE_MODULE_RPATH_VALUE=/usr/local/lib64 \
        -DCOMPOSITE_USE_NATS=OFF \
        -DCOMPOSITE_INSTALL=ON \
        -DCMAKE_INSTALL_PREFIX=/opt/usr/local \
        -DCMAKE_BUILD_TYPE=Release; \
    cmake --build docker-build --target install --parallel 4

FROM base

RUN microdnf install -y libstdc++ vim fftw libatomic numactl

COPY --link --from=project /opt/usr/local /usr/local
COPY --link --from=project /opt/usr/local/bin/composite-cli /usr/local/bin/composite-cli-priv
COPY --from=project /opt/dpdk/lib /opt/dpdk/lib
COPY --from=dpdk-build /usr/local/bin /usr/local/bin

RUN setcap cap_net_raw+ep /usr/local/bin/composite-cli-priv

COPY examples /usr/local/share/composite/examples
RUN chmod a+r /usr/local/share/composite/examples/*.json

ENV LD_LIBRARY_PATH=/usr/local/lib64
ENV BIN_ARGS=""
ENV PKG_CONFIG_PATH="/opt/dpdk/lib/pkgconfig:$PKG_CONFIG_PATH"
ENV LD_LIBRARY_PATH="/opt/dpdk/lib:$LD_LIBRARY_PATH"

# USER composite-dev
WORKDIR /home/composite-dev

CMD /usr/local/bin/composite-cli ${BIN_ARGS}
