FROM alpine:3.21 AS base

LABEL maintainer="Geon Technologies" \
      description="composite-based components"

RUN apk update && apk upgrade

RUN adduser -D composite-dev -s /bin/sh

FROM base AS build

RUN set -ex; \
    apk add --no-cache build-base; \
    apk add --no-cache gdb; \
    apk add --no-cache cmake; \
    apk add --no-cache git; \
    apk add --no-cache linux-headers; \
    apk add --no-cache fftw-dev;

FROM build AS project

COPY include /opt/composite-comps/include
COPY src /opt/composite-comps/src
COPY CMakeLists.txt /opt/composite-comps
WORKDIR /opt/composite-comps

RUN set -ex; \
    cmake -B docker-build \
        -DCOMPOSITE_USE_NATS=ON \
        -DCOMPOSITE_INSTALL=ON \
        -DCMAKE_INSTALL_PREFIX=/opt/usr/local \
        -DCMAKE_BUILD_TYPE=Release; \
    cmake --build docker-build --target install --parallel 4

FROM base

RUN apk add --no-cache libstdc++ fftw

COPY --link --from=project /opt/usr/local /usr/local

COPY examples /usr/local/share/composite/examples
RUN chmod a+r /usr/local/share/composite/examples/*.json

ENV LD_LIBRARY_PATH=/usr/local/lib
ENV BIN_ARGS=""

USER composite-dev
WORKDIR /home/composite-dev

CMD /usr/local/bin/composite-cli ${BIN_ARGS}
